function [] = print_map_stats3(stats)


%%
fprintf('#flips=%d, sigma_ratio: max=%g, mean=%g, MIPS-2=%g\n', ...
    stats.num_flips, ...
    max(stats.sigma_ratio), ...
    mean(stats.sigma_ratio), ...
    sum(stats.wavg_MIPS) - 2 ... % wavg_MIPS
    ); 

